google.maps.__gjsload__('visualization_impl', function(_){var W4=function(a){for(var b=Array(a),c=0;c<a;++c)b[c]=0;c=Array(a);for(var d=0;d<a;++d)c[d]=b.concat();return c},X4=function(a){if(!a||!a.getLength())return 1;var b=new _.vc;a.forEach(function(a){a&&b.extend(a.location?a.location:a)});var c=b.f.b,d=b.b.b,e=Math.max(b.f.f-c,b.b.f-d);if(1E-9>e){var f=0;a.forEach(function(a){a instanceof _.L?++f:f+=a.weight});return Math.max(1,f)}var g=800/e,h=W4(800),k=1;a.forEach(function(a){if(a){var b=a.location?a.location:a;a=a.weight||1;b=new _.H(Math.max(0,Math.min(799,
Math.floor((b.lat()-c)*g))),Math.max(0,Math.min(799,Math.floor((b.lng()-d)*g))));h[b.x][b.y]+=a;k=Math.max(k,h[b.x][b.y])}});return k},Z4=function(a,b){var c=[],d=[],e=1E3/(a.length-1);_.D(a,function(a,b){c.push(b*e);d.push(_.yI(a))});a=Array(1001);for(var f=0,g=0;1001>g;++g)g>c[f+1]&&++f,a[g]=f<c.length-1?Y4(e*f,g,e*(f+1),d[f],d[f+1]):d[d.length-1],a[g].alpha*=b,a[g].alpha=_.Ab(Math.floor(255*a[g].alpha),0,255);return a},Y4=function(a,b,c,d,e){if(a==c)return d;a=(b-a)/(c-a);return new _.vI(Math.floor((e.j-
d.j)*a+d.j),Math.floor((e.f-d.f)*a+d.f),Math.floor((e.b-d.b)*a+d.b),(e.alpha-d.alpha)*a+d.alpha)},$4=function(a,b){this.l=a;this.f=b;this.b=1;this.j=[]},b5=function(a,b,c){_.Bl(b.Z,"");if(_.Tw()){var d=b.ownerDocument,e,f=e=d.createElement("canvas");_.Hl(f);f.width=f.height=256;f=f.getContext("2d");var g=1<a.b;b.Z.appendChild(e);b=a5(a,b);e=a.j;for(var h=Math.floor(e.length/2),k=b.length,n=k-h,p=W4(k),q=0;q<k;++q)for(var t=b[q],u=p[q],x=0;x<k;++x){var v=t[x];if(v)for(var z=x-h,B=Math.min(n,x+h+1),
C=Math.max(h,z);C<B;++C)u[C]+=v*e[C-z]}b=W4(k-2*h);for(q=0;q<k;++q)for(t=p[q],u=Math.max(h,q-h),x=Math.min(n,q+h+1),v=q-h,z=h,B=0;z<n;++z,++B)if(C=t[z])for(var J=u;J<x;++J)b[J-h][B]+=C*e[J-v];e=Math.ceil(256/a.b);e=f.createImageData(e,e);h=a.get("gradient");k=h[h.length-1];c=h.length/c;n=e.data;q=p=0;for(t=b.length;q<t;++q)for(u=b[q],x=0,v=u.length;x<v;++x)(z=u[x])||h[0].alpha?(z=h[Math.floor(z*c)]||k,n[p++]=z.j,n[p++]=z.f,n[p++]=z.b,n[p++]=z.alpha):p+=4;g?(d=d.createElement("canvas"),d.width=d.height=
256/a.b,d.getContext("2d").putImageData(e,0,0),f.scale(a.b,a.b),f.drawImage(d,0,0)):f.putImageData(e,0,0)}},a5=function(a,b){var c=a.get("projection");c=_.Yl(c);var d=a.get("radius");d=Math.round(d/a.b)*a.b;var e=b.Lb,f=(256+2*d)/a.b,g=W4(f),h;for(h in e){var k=e[h],n=c.fromLatLngToPoint(new _.L(k.N,k.P,!0)),p=c.fromLatLngToPoint(new _.L(k.T,k.U,!0)),q=null;q=_.gj(a.f,new _.dc(n.x,n.y),b.zoom,_.na());p=_.gj(a.f,new _.dc(p.x,p.y),b.zoom,_.na());n=d/256;q=_.fj(a.f,{L:Math.min(q.L,p.L)+n,M:Math.min(q.M,
p.M)+n,$:b.zoom});q=new _.H(q.I,q.J);k=a.l.search(k);p=0;for(n=k.length;p<n;++p){var t=k[p],u=c.fromLatLngToPoint(new _.L(t.oa.x,t.oa.y)),x=0,v=0;u=_.Zu(a.f,new _.dc(u.x,u.y),new _.dc(q.x,q.y),b.zoom);x=Math.floor(256*u.L);v=Math.floor(256*u.M);u=Math.floor((v+d)/a.b);x=Math.floor((x+d)/a.b);0<=u&&u<f&&0<=x&&x<f&&(g[u][x]+=t.weight)}}return g},g5=function(a,b){b=void 0===b?_.hi:b;_.zg.call(this);var c=this;this.m=b;this.D=new _.I(256,256);this.b={};b=_.kc(-100,-300,100,300);this.A=new _.rD(b,void 0);
b=_.kc(-90,-180,90,180);this.j=_.tI(b,function(a,b){return a.oa.ba(b.oa)&&a.weight==b.weight});this.aa=[];this.B=new _.ed;this.f=0;this.l=new $4(this.j,this.m);this.l.bindTo("projection",this,"projection",!0);this.l.bindTo("gradient",this,"gradient",!0);this.l.bindTo("radius",this,"radius",!0);a(this.B,function(a){return b5(c.l,a,c.f)});this.H=new _.qo(function(){var a=c.f;c.f=c5(c);_.Cb(a,c.f)||d5(c)},0);this.addListener("data_changed",function(){return e5(c)});this.addListener("maxintensity_changed",
function(){c.f=c5(c);d5(c)});this.addListener("gradient_changed",function(){d5(c)});this.addListener("opacity_changed",function(){var a=c.get("opacity"),b;for(b in c.b)c.b.hasOwnProperty(b)&&_.sw(c.b[b].Z,a)});this.addListener("radius_changed",function(){for(var a in c.b)if(c.b.hasOwnProperty(a)){var b=c.b[a],f=void 0,g=b.Lb;for(f in g)g.hasOwnProperty(f)&&c.A.remove(g[f]);b.Lb={};f5(c,b)}d5(c)});this.triggersTileLoadEvent=!0},f5=function(a,b){var c={L:b.ia.x,M:b.ia.y,$:b.zoom},d=a.get("radius"),
e=_.Yl(a.get("projection")),f=_.fj(a.m,c);f=new _.H(f.I,f.J);d=_.hj(a.m,c,d/256);c=d.min;d=d.max;c=_.kc(c.I,c.J,d.I,d.J);_.uI(c,e,f,function(c){c.b=b;b.Lb[_.Oc(c)]=c;_.sD(a.A,c)})},c5=function(a){var b=a.get("maxIntensity");return 1<=b?b:X4(a.get("data"))},e5=function(a){a.j.clear();var b=a.get("data");b&&(b.forEach(function(b){b&&_.sI(a.j,h5(b))}),a.H.j());d5(a);for(var c=_.Aa(a.aa),d=c.next();!d.done;d=c.next())_.M.removeListener(d.value);a.aa=b?[b.addListener("insert_at",function(b){return i5(a,
b)}),b.addListener("remove_at",function(b,c){return j5(a,c)}),b.addListener("set_at",function(b,c){j5(a,c);i5(a,b)})]:[]},i5=function(a,b){if(b=a.get("data").getAt(b))b=h5(b),_.sI(a.j,b),a.H.j(),k5(a,b.oa)},j5=function(a,b){b&&(b=h5(b),a.j.remove(b),a.H.j(),k5(a,b.oa))},k5=function(a,b){b=_.uD(a.A,b);b=_.Aa(b);for(var c=b.next();!c.done;c=b.next())_.hd(a.B,c.value.b)},d5=function(a){for(var b in a.b)a.b.hasOwnProperty(b)&&_.hd(a.B,a.b[b])},h5=function(a){var b=a.location?a.location:a;a=a.weight||
1;return{oa:new _.H(b.lat(),b.lng()),weight:a}},l5=function(a,b){var c=new _.MB(_.OB(250));this.b=a;a.b=(0,_.y)(this.j,this);this.m=b;this.f=c},m5=_.l(),n5="rgba(102, 255, 0, 0);rgba(102, 255, 0, 1);rgba(147, 255, 0, 1);rgba(193, 255, 0, 1);rgba(238, 255, 0, 1);rgba(244, 227, 0, 1);rgba(249, 198, 0, 1);rgba(255, 170, 0, 1);rgba(255, 113, 0, 1);rgba(255, 57, 0, 1);rgba(255, 0, 0, 1)".split(";");_.A($4,_.N);$4.prototype.radius_changed=function(){var a=this.get("radius");_.Tw()?this.b=20>a?1:2:this.b=4;a=Math.round(a/this.b);for(var b=a/3,c=[],d=-a;d<=a;d++)c.push(Math.exp(-d*d/(2*b*b)));this.j=c};_.sj(g5,_.zg);g5.prototype.Ha=function(){return{tileSize:{W:this.D.width,Y:this.D.height},sa:this.m,cb:!0,hb:3,Wa:this.da.bind(this)}};
g5.prototype.da=function(a,b){var c=this;b=void 0===b?{}:b;var d=void 0===b.wa?_.l():b.wa,e=void 0===b.Na?_.l():b.Na,f=!1,g=window.document.createElement("div");_.Ef(g,this.D);b=this.get("opacity");void 0!==b&&_.sw(g,b);var h={Z:g,zoom:a.$,ia:new _.H(a.L,a.M),Lb:{},ownerDocument:window.document};g.za=h;this.b[_.Oc(h)]=h;f5(this,h);this.f||(this.f=c5(this));b5(this.l,h,this.f);_.pb(function(){f=!0;d()});return{Ba:function(){return g},Gb:function(){return f},ia:a,release:function(){_.Bl(g,"");delete c.b[_.Oc(h)];
e()},freeze:_.l()}};g5.prototype.releaseTile=function(a){if(a){var b=a.za;a.za=null;delete this.b[_.Oc(b)];a=this.A;for(var c in b.Lb)b.Lb.hasOwnProperty(c)&&a.remove(b.Lb[c]);_.Bl(b.Z,"")}};l5.prototype.j=function(){_.NB(this.f,(0,_.y)(this.l,this))};l5.prototype.l=function(){a:{var a=this.b.f;for(var b in a){a=a[b];this.b.remove(a);break a}a=null}a&&this.m(a)};m5.prototype.b=function(a){var b=a.j,c=a.j=a.get("map");b&&(a.b&&(a.b.unbindAll(),a.b=null),a.f&&(a.f.release(),a.f=null),_.Gm("Lh","-p",a));if(c){var d=function(){k&&k.unbindAll();k=new g5(g,h);c&&k.bindTo("projection",c);k.bindTo("data",a);k.bindTo("maxIntensity",a);k.bindTo("gradient",e,"colorGradient");k.bindTo("radius",f,"renderingRadius");a.b&&(k.bindTo("opacity",a.b),e.set("opacity",1))};a.b=new _.rr({dissipating:!0,gradient:n5,opacity:.6,radius:10});a.b.bindTo("dissipating",a);a.b.bindTo("gradient",
a);a.b.bindTo("opacity",a);a.b.bindTo("radius",a);var e=new _.Rw(["stringGradient","opacity"],"colorGradient",function(a,b){return Z4(a,b)});e.bindTo("stringGradient",a.b,"gradient",!0);var f=new _.Rw(["radius","dissipating","zoom"],"renderingRadius",function(a,b,c){return b?a:Math.min(Math.round(a*Math.pow(2,c)),256)});f.bindTo("radius",a.b);f.bindTo("zoom",c);f.bindTo("dissipating",a.b);var g=function(a,b){new l5(a,b)};b=c.__gm;var h=void 0,k=null;d();var n=k.Ha(),p=_.md(n);b.b.then(function(a){_.Zc(a.Uc,
function(a){a&&h!=a.sa&&(h=a.sa,d(),p.set(k.Ha()))})});_.pD(c,p,"overlayLayer",15,{Zh:function(b){a.f&&a.f.release();a.f=b}});_.X(c,"Lh");_.Fm("Lh","-p",a)}};_.de("visualization_impl",new m5);});
